server:
  port: 8081
  servlet:
    context-path: /hustleFreeThrift
custom:
  security:
    username: local
    password: local
spring:
  jackson:
    time-zone: Asia/Kolkata
  servlet:
    multipart:
      enabled: true
      max-file-size: 5242880
      max-request-size: 31457280
  active-mq:
    broker-url: tcp://localhost:61616
    packages:
      trust-all: false
      trusted: com.thrift.hft
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      enabled: false
      idle-timeout: 30000
      max-connections: 1
      time-between-expiration-check: -1
      use-anonymous-producers: true
  jms:
     listener:
        concurrency: 1
        max-concurrency: 1
     template:
          delivery-mode: non_persistent
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/HFT
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    hikari:
      connection-timeout: 5000
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 268230345751-n10fj0htcqvu851lmr4c5afvnt81cgqg.apps.googleusercontent.com
            client-secret: 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
            scope: email,profile
hft:
  jwt:
    secret-key: "9y$B&E)H@McQeThWmZq4t7w!z%C*F-JaNdRgUjXn2r5u8x/A?D(G+KbPeShVmYp3"
    expiry-time: 60000000
  queue:
    sell-request-queue: sell-request-queue
  document-path:
    base-path: "/home/neosoft/Documents/HFT/documents/"
    product-images: "product/images/"

app:
  cors:
    origins: ${CORS_ORIGINS:http://localhost:8081/,http://localhost:4200}